# Railway deployment configuration
[variables]
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT"