services:
  - type: web
    name: telegram-otp-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_GROUP_ID
        sync: false
      - key: IVASMS_EMAIL
        sync: false
      - key: IVASMS_PASSWORD
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: DATABASE_URL
        value: sqlite:///bot.db
      - key: DEBUG
        value: "0"